{"nodes":[{"pos":[12,49],"content":"Compiler Error C2705 | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Compiler Error C2705 | Microsoft Docs","pos":[0,37]}]},{"pos":[597,617],"content":"Compiler Error C2705","linkify":"Compiler Error C2705","nodes":[{"content":"Compiler Error C2705","pos":[0,20]}]},{"content":"'label' : illegal jump into 'exception handler block' scope","pos":[618,677]},{"content":"Execution jumps to a label within a <ph id=\"ph1\">`try`</ph><ph id=\"ph2\">/</ph><ph id=\"ph3\">`catch`</ph>, <ph id=\"ph4\">`__try`</ph><ph id=\"ph5\">/</ph><ph id=\"ph6\">`__except`</ph>, <ph id=\"ph7\">`__try`</ph><ph id=\"ph8\">/</ph><ph id=\"ph9\">`__finally`</ph> block.","pos":[684,781],"source":"Execution jumps to a label within a `try`/`catch`, `__try`/`__except`, `__try`/`__finally` block."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../cpp/exception-handling-in-visual-cpp.md)</ept>.","pos":[782,876],"source":" For more information, see [Exception Handling](../../cpp/exception-handling-in-visual-cpp.md)."},{"content":"The following sample generates C2705:","pos":[883,920]}],"content":"---\ntitle: \"Compiler Error C2705 | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"error-reference\"\nf1_keywords: \n  - \"C2705\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"C2705\"\nms.assetid: 29249ea3-4ea7-4105-944b-bdb83e8d6852\ncaps.latest.revision: 9\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Compiler Error C2705\n'label' : illegal jump into 'exception handler block' scope  \n  \n Execution jumps to a label within a `try`/`catch`, `__try`/`__except`, `__try`/`__finally` block. For more information, see [Exception Handling](../../cpp/exception-handling-in-visual-cpp.md).  \n  \n The following sample generates C2705:  \n  \n```  \n// C2705.cpp  \nint main() {  \ngoto trouble;  \n   __try {  \n      trouble: ;   // C2705  \n   }  \n   __finally {}  \n  \n   // try the following line instead  \n   // trouble: ;  \n}  \n```"}