{"nodes":[{"pos":[12,47],"content":"_CxxThrowException | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"_CxxThrowException | Microsoft Docs","pos":[0,35]}]},{"pos":[985,1003],"content":"_CxxThrowException","linkify":"_CxxThrowException","nodes":[{"content":"_CxxThrowException","pos":[0,18]}]},{"content":"Builds the exception record and calls the runtime environment to start processing the exception.","pos":[1004,1100]},{"pos":[1109,1115],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[1250,1260],"content":"Parameters","linkify":"Parameters","nodes":[{"content":"Parameters","pos":[0,10]}]},{"content":"[in] <ph id=\"ph1\">`pExceptionObject`</ph>","pos":[1264,1287],"source":"[in] `pExceptionObject`"},{"content":"The object that generated the exception.","pos":[1291,1331]},{"content":"[in] <ph id=\"ph1\">`pThrowInfo`</ph>","pos":[1338,1355],"source":"[in] `pThrowInfo`"},{"content":"The information that is required to process the exception.","pos":[1359,1417]},{"pos":[1426,1433],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This method is included in a compiler-only file that the compiler uses to process exceptions.","pos":[1437,1530]},{"content":"Do not call the method directly from your code.","pos":[1531,1578]},{"pos":[1587,1599],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[1603,1624],"content":"<bpt id=\"p1\">**</bpt>Source:<ept id=\"p1\">**</ept> Throw.cpp","source":"**Source:** Throw.cpp"},{"pos":[1633,1641],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"pos":[1645,1752],"content":"<bpt id=\"p1\">[</bpt>Alphabetical Function Reference<ept id=\"p1\">](../../c-runtime-library/reference/crt-alphabetical-function-reference.md)</ept>","source":"[Alphabetical Function Reference](../../c-runtime-library/reference/crt-alphabetical-function-reference.md)"}],"content":"---\ntitle: \"_CxxThrowException | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\napiname: \n  - \"_CxxThrowException\"\napilocation: \n  - \"msvcrt.dll\"\n  - \"msvcr80.dll\"\n  - \"msvcr90.dll\"\n  - \"msvcr100.dll\"\n  - \"msvcr100_clr0400.dll\"\n  - \"msvcr110.dll\"\n  - \"msvcr110_clr0400.dll\"\n  - \"msvcr120.dll\"\n  - \"msvcr120_clr0400.dll\"\n  - \"ucrtbase.dll\"\napitype: \"DLLExport\"\nf1_keywords: \n  - \"CxxThrowException\"\n  - \"_CxxThrowException\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"_CxxThrowException function\"\n  - \"CxxThrowException function\"\nms.assetid: 0b90bef5-b7d2-46e0-88e2-59e531e01a4d\ncaps.latest.revision: 8\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# _CxxThrowException\nBuilds the exception record and calls the runtime environment to start processing the exception.  \n  \n## Syntax  \n  \n```  \nextern \"C\" void __stdcall _CxxThrowException(  \n   void* pExceptionObject  \n   _ThrowInfo* pThrowInfo  \n);  \n```  \n  \n#### Parameters  \n [in] `pExceptionObject`  \n The object that generated the exception.  \n  \n [in] `pThrowInfo`  \n The information that is required to process the exception.  \n  \n## Remarks  \n This method is included in a compiler-only file that the compiler uses to process exceptions. Do not call the method directly from your code.  \n  \n## Requirements  \n **Source:** Throw.cpp  \n  \n## See Also  \n [Alphabetical Function Reference](../../c-runtime-library/reference/crt-alphabetical-function-reference.md)"}